apiVersion: v1
kind: Service
metadata:
  name: laravel-service
spec:
  selector:
    app: laravel
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
      nodePort: 30000
  type: NodePort
